from jos.api.rest.TradeFullinfoGetRequest import TradeFullinfoGetRequest
from jos.api.rest.TradesSoldGetRequest import TradesSoldGetRequest
from jos.api.rest.TradesSoldIncrementGetRequest import TradesSoldIncrementGetRequest